<?php

return [
    /**
     * MercadoPago Checkout Pro Configuration
     */
    [
        'key'    => 'sales.payment_methods.mercadopago_checkout_pro',
        'name'   => 'mercadopago::app.admin.payment-methods.checkout-pro.name',
        'info'   => 'mercadopago::app.admin.payment-methods.checkout-pro.info',
        'sort'   => 5,
        'fields' => [
            [
                'name'          => 'title',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.title',
                'type'          => 'text',
                'default'       => 'MercadoPago Checkout Pro',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'description',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.description',
                'type'          => 'textarea',
                'default'       => 'Pay securely with MercadoPago - Credit Cards, Debit Cards, and more',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'logo',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type'          => 'image',
                'info'          => 'admin::app.configuration.index.sales.payment-methods.logo-information',
                'channel_based' => true,
            ], [
                'name'          => 'access_token',
                'title'         => 'mercadopago::app.admin.payment-methods.access-token',
                'info'          => 'mercadopago::app.admin.payment-methods.access-token-info',
                'type'          => 'password',
                'validation'    => 'required',
                'channel_based' => true,
            ], [
                'name'          => 'public_key',
                'title'         => 'mercadopago::app.admin.payment-methods.public-key',
                'info'          => 'mercadopago::app.admin.payment-methods.public-key-info',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
            ], [
                'name'          => 'webhook_secret',
                'title'         => 'mercadopago::app.admin.payment-methods.webhook-secret',
                'info'          => 'mercadopago::app.admin.payment-methods.webhook-secret-info',
                'type'          => 'password',
                'channel_based' => true,
            ], [
                'name'          => 'sandbox',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type'          => 'boolean',
                'default'       => true,
                'channel_based' => true,
            ], [
                'name'          => 'auto_return',
                'title'         => 'mercadopago::app.admin.payment-methods.auto-return',
                'info'          => 'mercadopago::app.admin.payment-methods.auto-return-info',
                'type'          => 'select',
                'default'       => 'approved',
                'options'       => [
                    [
                        'title' => 'mercadopago::app.admin.payment-methods.auto-return-approved',
                        'value' => 'approved',
                    ], [
                        'title' => 'mercadopago::app.admin.payment-methods.auto-return-all',
                        'value' => 'all',
                    ],
                ],
                'channel_based' => true,
            ], [
                'name'          => 'max_installments',
                'title'         => 'mercadopago::app.admin.payment-methods.max-installments',
                'info'          => 'mercadopago::app.admin.payment-methods.max-installments-info',
                'type'          => 'select',
                'default'       => '12',
                'options'       => [
                    ['title' => '1', 'value' => '1'],
                    ['title' => '2', 'value' => '2'],
                    ['title' => '3', 'value' => '3'],
                    ['title' => '6', 'value' => '6'],
                    ['title' => '9', 'value' => '9'],
                    ['title' => '12', 'value' => '12'],
                    ['title' => '15', 'value' => '15'],
                    ['title' => '18', 'value' => '18'],
                    ['title' => '24', 'value' => '24'],
                ],
                'channel_based' => true,
            ], [
                'name'          => 'exclude_payment_types',
                'title'         => 'mercadopago::app.admin.payment-methods.exclude-payment-types',
                'info'          => 'mercadopago::app.admin.payment-methods.exclude-payment-types-info',
                'type'          => 'multiselect',
                'options'       => [
                    [
                        'title' => 'mercadopago::app.admin.payment-methods.credit-card',
                        'value' => 'credit_card',
                    ], [
                        'title' => 'mercadopago::app.admin.payment-methods.debit-card',
                        'value' => 'debit_card',
                    ], [
                        'title' => 'mercadopago::app.admin.payment-methods.bank-transfer',
                        'value' => 'bank_transfer',
                    ], [
                        'title' => 'mercadopago::app.admin.payment-methods.digital-wallet',
                        'value' => 'digital_wallet',
                    ], [
                        'title' => 'mercadopago::app.admin.payment-methods.ticket',
                        'value' => 'ticket',
                    ],
                ],
                'channel_based' => true,
            ], [
                'name'          => 'binary_mode',
                'title'         => 'mercadopago::app.admin.payment-methods.binary-mode',
                'info'          => 'mercadopago::app.admin.payment-methods.binary-mode-info',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
            ], [
                'name'          => 'active',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.status',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
            ], [
                'name'          => 'auto_return',
                'title'         => 'mercadopago::app.admin.system.auto-return',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'sort',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type'          => 'select',
                'default'       => '5',
                'options'       => [
                    ['title' => '1', 'value' => '1'],
                    ['title' => '2', 'value' => '2'],
                    ['title' => '3', 'value' => '3'],
                    ['title' => '4', 'value' => '4'],
                    ['title' => '5', 'value' => '5'],
                    ['title' => '6', 'value' => '6'],
                    ['title' => '7', 'value' => '7'],
                    ['title' => '8', 'value' => '8'],
                    ['title' => '9', 'value' => '9'],
                    ['title' => '10', 'value' => '10'],
                ],
            ],
        ],
    ],

    /**
     * MercadoPago Checkout API Configuration
     */
    [
        'key'    => 'sales.payment_methods.mercadopago_checkout_api',
        'name'   => 'mercadopago::app.admin.payment-methods.checkout-api.name',
        'info'   => 'mercadopago::app.admin.payment-methods.checkout-api.info',
        'sort'   => 6,
        'fields' => [
            [
                'name'          => 'title',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.title',
                'type'          => 'text',
                'default'       => 'MercadoPago Checkout API',
                'validation'    => 'required',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'description',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.description',
                'type'          => 'textarea',
                'default'       => 'Pay directly on our website with your credit or debit card',
                'channel_based' => true,
                'locale_based'  => true,
            ], [
                'name'          => 'logo',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type'          => 'image',
                'info'          => 'admin::app.configuration.index.sales.payment-methods.logo-information',
                'channel_based' => true,
            ], [
                'name'          => 'access_token',
                'title'         => 'mercadopago::app.admin.payment-methods.access-token',
                'info'          => 'mercadopago::app.admin.payment-methods.access-token-info',
                'type'          => 'password',
                'validation'    => 'required',
                'channel_based' => true,
            ], [
                'name'          => 'public_key',
                'title'         => 'mercadopago::app.admin.payment-methods.public-key',
                'info'          => 'mercadopago::app.admin.payment-methods.public-key-info',
                'type'          => 'text',
                'validation'    => 'required',
                'channel_based' => true,
            ], [
                'name'          => 'webhook_secret',
                'title'         => 'mercadopago::app.admin.payment-methods.webhook-secret',
                'info'          => 'mercadopago::app.admin.payment-methods.webhook-secret-info',
                'type'          => 'password',
                'channel_based' => true,
            ], [
                'name'          => 'sandbox',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type'          => 'boolean',
                'default'       => true,
                'channel_based' => true,
            ], [
                'name'          => 'capture_payment',
                'title'         => 'mercadopago::app.admin.payment-methods.capture-payment',
                'info'          => 'mercadopago::app.admin.payment-methods.capture-payment-info',
                'type'          => 'boolean',
                'default'       => true,
                'channel_based' => true,
            ], [
                'name'          => 'save_customer_cards',
                'title'         => 'mercadopago::app.admin.payment-methods.save-customer-cards',
                'info'          => 'mercadopago::app.admin.payment-methods.save-customer-cards-info',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
            ], [
                'name'          => 'statement_descriptor',
                'title'         => 'mercadopago::app.admin.payment-methods.statement-descriptor',
                'info'          => 'mercadopago::app.admin.payment-methods.statement-descriptor-info',
                'type'          => 'text',
                'validation'    => 'max:22',
                'channel_based' => true,
            ], [
                'name'          => 'installments_enabled',
                'title'         => 'mercadopago::app.admin.payment-methods.installments-enabled',
                'info'          => 'mercadopago::app.admin.payment-methods.installments-enabled-info',
                'type'          => 'boolean',
                'default'       => true,
                'channel_based' => true,
            ], [
                'name'          => 'max_installments',
                'title'         => 'mercadopago::app.admin.payment-methods.max-installments',
                'info'          => 'mercadopago::app.admin.payment-methods.max-installments-info',
                'type'          => 'select',
                'default'       => '12',
                'depends'       => 'installments_enabled:true',
                'options'       => [
                    ['title' => '1', 'value' => '1'],
                    ['title' => '2', 'value' => '2'],
                    ['title' => '3', 'value' => '3'],
                    ['title' => '6', 'value' => '6'],
                    ['title' => '9', 'value' => '9'],
                    ['title' => '12', 'value' => '12'],
                    ['title' => '15', 'value' => '15'],
                    ['title' => '18', 'value' => '18'],
                    ['title' => '24', 'value' => '24'],
                ],
                'channel_based' => true,
            ], [
                'name'          => 'debug_mode',
                'title'         => 'mercadopago::app.admin.payment-methods.debug-mode',
                'info'          => 'mercadopago::app.admin.payment-methods.debug-mode-info',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
            ], [
                'name'          => 'active',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.status',
                'type'          => 'boolean',
                'default'       => false,
                'channel_based' => true,
            ], [
                'name'          => 'sort',
                'title'         => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type'          => 'select',
                'default'       => '6',
                'options'       => [
                    ['title' => '1', 'value' => '1'],
                    ['title' => '2', 'value' => '2'],
                    ['title' => '3', 'value' => '3'],
                    ['title' => '4', 'value' => '4'],
                    ['title' => '5', 'value' => '5'],
                    ['title' => '6', 'value' => '6'],
                    ['title' => '7', 'value' => '7'],
                    ['title' => '8', 'value' => '8'],
                    ['title' => '9', 'value' => '9'],
                    ['title' => '10', 'value' => '10'],
                ],
            ],
        ],
    ],
];
